export const descriptionData = {
    "Câu chuyện của Nàng Bạch Tuyết ban đầu cũng giống như cổ tích, khi nàng công chúa mới chào đời, mang niềm vui và sự ấm áp tới cả vương quốc xinh đẹp. Mẹ mất sớm, cha bao bọc nàng bằng tất cả tình yêu thương, dạy nàng phải sống không sợ hãi, công bằng, dũng cảm và chân thành. Bạch Tuyết càng lớn lên càng lay động lòng người, với vẻ đẹp thuần khiết như ánh nắng ban mai và một trái tim thiện lương, nhân hậu. Thế nhưng, những ngày tháng vui vẻ không kéo dài lâu khi cha cô cũng qua đời. Ngày hoàng hậu mới lên ngôi, bóng tối bao trùm cả vương quốc. Độc ác và đầy dã tâm, ả không có lòng khoan dung, sẵn sàng trừng phạt bất cứ ai dám làm trái lệnh. Sự ghen ghét, đố kỵ của mẹ kế đẩy Bạch Tuyết vào cảnh nguy hiểm. Nàng phải chạy trốn vào rừng sâu, nơi cuộc phiêu lưu của nàng bắt đầu với những người bạn tốt bụng mới.": {
        en: "Snow White's story began like a fairy tale, when the young princess was born, bringing joy and warmth to the entire beautiful kingdom. Her mother passed away early, and her father protected her with all his love, teaching her to live fearlessly, justly, bravely, and sincerely. As she grew up, Snow White touched everyone’s hearts with her pure beauty like the morning sunlight and a kind, compassionate heart. However, the joyful days didn’t last long, as her father also passed away. On the day the new queen ascended the throne, darkness fell upon the kingdom. Cruel and ambitious, she was intolerant and ready to punish anyone who disobeyed her orders. The stepmother's jealousy and envy pushed Snow White into danger. She had to flee deep into the forest, where her adventure began with new kind-hearted friends."
    },
    "Thông qua món bảo bối mới của Doraemon, cả nhóm bạn bước thế giới trong một bức tranh nổi tiếng và bắt gặp cô bạn bí ẩn tên Claire. Với lời mời của Claire, cả nhóm cùng đến thăm vương quốc Artoria, nơi ẩn giấu một viên ngọc quý mang tên Artoria Blue đang ngủ yên. Trên hành trình tìm kiếm viên ngọc, nhóm bạn Doraemon phát hiện một truyền thuyết về sự hủy diệt của thế giới, mà truyền thuyết đó dường như đang sống dậy! Liệu cả nhóm có thể phá hủy lời nguyền này và bảo vệ cả thế giới?": {
        en: "Through one of Doraemon's new gadgets, the group steps into the world of a famous painting and meets a mysterious girl named Claire. At Claire’s invitation, they visit the kingdom of Artoria, which hides a precious gem called Artoria Blue that lies dormant. On their journey to find the gem, Doraemon and friends discover a legend about the world's destruction—a legend that now seems to be coming true! Can they break the curse and save the world?"
    },
    "Levon Cade - cựu biệt kích tinh nhuệ thuộc lực lượng Thủy quân Lục chiến Hoàng gia Anh. Sau khi nghỉ hưu, anh sống cuộc đời yên bình là một công nhân xây dựng tại Chicago (Mỹ). Levon có mối quan hệ rất tốt với gia đình ông chủ Joe Garcia (Michael Peña). Một ngày nọ, cô con gái tuổi teen Jenny (Arianna Rivas) của Joe bị bắt cóc khiến chàng cựu quân nhân phải sử dụng lại các kỹ năng giết chóc của mình để giúp đỡ.": {
        en: "Levon Cade is a former elite commando of the Royal Marines. After retiring, he lives a peaceful life as a construction worker in Chicago (USA). Levon has a close relationship with the family of his boss, Joe Garcia (Michael Peña). One day, Joe’s teenage daughter Jenny (Arianna Rivas) is kidnapped, forcing the ex-soldier to use his deadly skills once again to help rescue her."
    },
    "Câu chuyện xoay quanh PANOR, một cô gái trẻ ngây thơ sinh ra vào ngày đen tối khi một người nào đó trong làng giải phóng lời nguyền ma thuật đen. Panor được coi là điềm xấu, một người phụ nữ bị nguyền rủa mang lại vận rủi cho ngôi làng và bất kỳ ai dành thời gian với cô đều có nguy cơ trở thành nạn nhân của ma thuật đen. Panor sớm phát hiện ra rằng có thứ gì đó đen tối và mạnh mẽ đã theo dõi cô kể từ ngày cô được sinh ra, nguyền rủa cô phải sống một cuộc sống khốn khổ.": {
        en: "The story revolves around PANOR, an innocent young girl born on a dark day when someone in the village unleashed a curse of dark magic. Panor is considered a bad omen—a cursed woman who brings misfortune to the village, and anyone who spends time with her risks becoming a victim of black magic. Panor soon discovers that something dark and powerful has been watching her since the day she was born, condemning her to a life of misery."
    },
    "Cơn ác mộng chưa kết thúc. Virus trở lại, kéo theo bóng tối bao trùm nước Anh. Một hành trình sinh tử: cậu bé tìm kiếm bác sĩ để cứu mẹ mình, băng qua vùng đất chết chóc đầy xác sống tiến hóa và những kẻ nguy hiểm ẩn sau gương mặt tử tế. Liệu niềm hy vọng cuối cùng có đủ để cứu họ khỏi vực thẳm tuyệt vọng?": {
        en: "The nightmare isn't over. The virus has returned, casting darkness over the UK. A life-or-death journey unfolds as a young boy searches for a doctor to save his mother, crossing a deadly land filled with evolved undead and dangerous individuals hiding behind kind faces. Will the last spark of hope be enough to save them from the abyss of despair?"
    },
    "MATERIALISTS xoay quanh Lucy (Dakota Johnson), một chuyên gia mai mối tình yêu tại New York, giúp đỡ khách hàng có thể tìm thấy “mảnh ghép hoàn hảo” của cuộc đời mình. “Mát tay” trong chuyện mai mối giúp người khác, nhưng trớ trêu thay, Lucy lại “lạc lối” trong câu chuyện tình cảm của chính mình. Cô nàng bị đẩy vào tình thế khó xử, khi đang hẹn hò với người đàn ông thành đạt, giàu có Randy (Pedro Pascal), thì anh bạn trai cũ tên John (Chris Evans) xuất hiện. Đứng giữa những lựa chọn cảm xúc đầy mâu thuẫn, lúc này đây, Lucy mới nhận ra việc tìm kiếm tình yêu đích thực chưa bao giờ là điều dễ dàng.": {
        en: "MATERIALISTS follows Lucy (Dakota Johnson), a professional matchmaker in New York who helps clients find their perfect match. While she’s great at helping others find love, ironically, Lucy is lost in her own romantic journey. Things become complicated when she’s dating a successful, wealthy man named Randy (Pedro Pascal), and her ex-boyfriend John (Chris Evans) suddenly reappears. Torn between conflicting emotions, Lucy realizes that finding true love has never been an easy task."
    },
    "Chốt Đơn! xoay quanh cuộc sống tất bật của Hoàng Linh - nữ “chiến thần” chốt đơn trẻ đang thành công và chú An (Quyền Linh) một nhân viên văn phòng kiêm tài xế xe ôm công nghệ. Giữa những mơ hồ, thay đổi, áp lực của xã hội lên hai thế hệ, Hoàng Linh và chú An vốn đối lập từ tuổi tác, hoàn cảnh đến tính cách, lại tìm thấy một tình bạn thật trong sáng, khởi tạo nên những nhiệt huyết mới để mang đến những phiên “Chốt đơn!” thắng đậm.": {
        en: "Chốt Đơn! revolves around the bustling lives of Hoàng Linh – a young and successful online sales “closer” – and Uncle An (played by Quyền Linh), an office worker who also drives for a ride-hailing service. Amid the uncertainties, changes, and pressures of society on two different generations, Hoàng Linh and Uncle An, though vastly different in age, background, and personality, discover a sincere friendship that sparks renewed passion and energy, leading to many successful 'closed deals'."
    },
    "Giữa mênh mông cát gió, có một cây xương rồng đã bắt đầu nở hoa. Theo cả nhà thì Vòng tay nắng mang ý nghĩa gì? - Cùng đón chờ!": {
        en: "Amidst the vast and windy desert, a cactus has begun to bloom. What do you think 'Vòng tay nắng' symbolizes? - Stay tuned to find out!"
    },

    "Sau sự ra đi của cha, Lan (Phương Thanh) về một vùng quê và ở đợ cho nhà ông Danh (Mạc Văn Khoa) - một người đàn ông góa vợ, không con cái. Ngay sau khi bước chân vào căn nhà, Lan phải đối mặt với hàng loạt hiện tượng kỳ dị và những cái chết bí ẩn liên tục xảy ra. Cùng với Sơn (Quốc Trường) - một nhà văn chuyên viết truyện kinh dị, Lan bắt đầu lật mở những bí mật kinh hoàng, khám phá lịch sử đen tối của căn nhà.": {
        en: "After her father's passing, Lan (Phương Thanh) returns to a rural village and becomes a maid in the home of Mr. Danh (Mạc Văn Khoa) – a widower with no children. From the moment she sets foot in the house, Lan encounters a series of eerie occurrences and mysterious deaths. Teaming up with Sơn (Quốc Trường), a horror fiction writer, Lan begins to uncover terrifying secrets and the dark history hidden within the house."
    },

    "Sau khi thầy Doi chấp nhận quyết đấu với Moroizumi Sonemon, ông đã mất tích không rõ tung tích. Khi nghe tin này, các thầy giáo cùng các học sinh lớp 6 lập tức tiến hành một cuộc tìm kiếm toàn diện. Giữa tình thế hỗn loạn, Kirimaru vô tình tìm được manh mối về tung tích của thầy Doi. Cùng lúc đó, trong khi nhóm học sinh lớp 6 đang ráo riết tìm kiếm, quân sư lạnh lùng của đội Ninja Dokutake - Tenki bất ngờ xuất hiện. Điều khiến mọi người kinh ngạc là khuôn mặt của Tenki lại giống hệt thầy Doi! Kẻ địch hùng mạnh đang ở trước mắt, các học viên Ninja của Học viện Nhẫn Thuật buộc phải thể hiện sự gắn kết mạnh mẽ mới có thể vượt qua thử thách chưa từng có này. Liệu Rantarou, Kirimaru và Shinbei có thể giải cứu thầy Doi thành công không?": {
        en: "After Master Doi accepted a duel with Moroizumi Sonemon, he mysteriously disappeared without a trace. Upon hearing the news, the teachers and sixth-grade students immediately launched a full-scale search. Amidst the chaos, Kirimaru accidentally discovers a clue to Master Doi’s whereabouts. At the same time, Tenki—the cold strategist of the Dokutake Ninja Army—suddenly appears. Shockingly, Tenki's face is identical to that of Master Doi! With a powerful enemy looming, the young ninja students of the Ninja Academy must unite stronger than ever to overcome this unprecedented challenge. Can Rantarou, Kirimaru, and Shinbei successfully rescue Master Doi?"
    },
    "Sonny Hayes (Brad Pitt) được mệnh danh là \"Huyền thoại chưa từng được gọi tên\" là ngôi sao sáng giá nhất của FORMULA 1 trong những năm 1990 cho đến khi một vụ tai nạn trên đường đua suýt nữa đã kết thúc sự nghiệp của anh.. Ba mươi năm sau, Sonny trở thành một tay đua tự do, cho đến khi người đồng đội cũ của anh, Ruben Cervantes (Javier Bardem), chủ sở hữu một đội đua F1 đang trên bờ vực sụp đổ, tìm đến anh. Ruben thuyết phục Sonny quay lại với F1® để có một cơ hội cuối cùng cứu lấy đội và khẳng định mình là tay đua xuất sắc nhất thế giới. Anh sẽ thi đấu cùng Joshua Pearce (Damson Idris), tay đua tân binh đầy tham vọng của đội, người luôn muốn tạo ra tốc độ của riêng mình. Tuy nhiên, khi động cơ gầm rú, quá khứ của Sonny sẽ đuổi theo anh và anh nhận ra rằng trong F1, người đồng đội chính là đối thủ cạnh tranh lớn nhất—và con đường chuộc lại lỗi lầm không phải là điều có thể đi một mình.": {
        en: "Sonny Hayes (Brad Pitt), known as the 'Legend Never Named', was the brightest star of Formula 1 in the 1990s—until a devastating crash nearly ended his career. Thirty years later, Sonny is a retired driver until his former teammate, Ruben Cervantes (Javier Bardem), now the desperate owner of a struggling F1 team, asks him to return. Ruben convinces Sonny to make a comeback for one last shot at saving the team and proving he is still the best in the world. He partners with rookie driver Joshua Pearce (Damson Idris), an ambitious young talent aiming to make his own mark. As the engines roar, Sonny’s past catches up with him, and he realizes that in F1, your teammate can also be your fiercest rival—and the road to redemption is never walked alone."
    },

    "Bộ đôi Tiến Luật và Ngô Kiến Huy, với nghề nghiệp \"độc lạ\" hốt xác và lái xe cứu thương, hứa hẹn mang đến những tràng cười không ngớt cho khán giả qua hành trình tìm xác có một không hai trên màn ảnh Việt. Nhờ sự trợ giúp của thế lực tâm linh, họ không chỉ đối mặt với những tình huống \"dở khóc dở cười\" mà còn khám phá ra những bí mật rợn người ẩn sau những thi thể. Liệu họ có hoàn thành nhiệm vụ \"khó nhằn\" này hay sẽ gặp phải những \"biến cố\" nào?": {
        en: "The comedic duo Tiến Luật and Ngô Kiến Huy take on the quirky roles of corpse collectors and ambulance drivers in a uniquely hilarious Vietnamese cinematic journey. With help from mysterious spiritual forces, they face a series of absurd yet terrifying situations and uncover chilling secrets hidden within the bodies they encounter. Will they be able to complete their bizarre mission, or will unexpected twists derail their adventure?"
    },

    "Cha sứ Park – một linh mục vốn là bác sĩ đã bị khai trừ sau khi thực hiện những nghi lễ trừ tà mà Giáo hội cho là cực đoan, bởi những người trong Giáo hội từ chối tin rằng những thế lực vô hình đang rình rập các linh hồn vô tội. Những tưởng cha Park an phận giải nghệ, một nhà sư đến từ ngôi chùa bí ẩn cất giữ những bí thuật bất ngờ tìm tới ông với một lời khẩn cầu: Bảo vệ một đứa trẻ tên Joon Hoo khỏi vị sư phụ đã hắc hóa của cậu bé. Cha Park buộc phải đối mặt với bóng ma quá khứ để giải cứu đứa trẻ và ngăn chặn bi kịch lặp lại.": {
        en: "Father Park—a former doctor turned priest—was excommunicated after performing exorcisms deemed too extreme by the Church, which refused to believe in the invisible forces threatening innocent souls. Having retreated into quiet retirement, Park is unexpectedly approached by a monk from a mysterious temple that guards ancient secrets. The monk pleads with him to protect a boy named Joon Hoo from his now-corrupted master. Father Park must confront the ghosts of his past to rescue the child and prevent history from repeating its dark tragedy."
    },
    "Phim xoay quanh công chúa băng giá Ila - con gái của Nữ hoàng Tuyết đang cai trị tại vùng đất Gương. Vốn là một cô bé tinh nghịch và khát khao khám phá thế giới, nhưng cô luôn bị mẹ quản nghiêm ngặt vì còn quá trẻ và chưa khai mở được bản năng phép thuật của mình. Một ngày, Ila tình cờ gặp gỡ 3 yêu tinh nhí. Họ là những du khách xuất hiện từ bên kia cánh cổng ma thuật. Ila quyết định kết bạn và hé lộ cho họ một bí mật tại vùng đất Gương. Ở hồ băng Gao có một phong ấn ma thuật bí ẩn - nơi giam giữ những linh hồn băng hàng nghìn năm. Trong lúc trổ tài trượt băng trên hồ Gao, Ila bất cẩn làm vỡ phong ấn khiến cho những linh hồn băng thoát ra ngoài. Để ngăn chặn mối nguy hiểm, Nữ hoàng Tuyết đã yêu cầu Ila cùng 3 yêu tính nhí đến thế giới loài người tìm kiếm Kai và Gerda, vì họ là những người duy nhất có thể giúp cô bé chống lại sức mạnh của những linh hồn băng. Từ đây, Ila bắt đầu hành trình khám phá thế giới mới với trọng trách to lớn nhằm chuộc lại lỗi lầm mà mình gây ra.": {
        en: "The film follows icy princess Ila, daughter of the Snow Queen who rules the mystical land of Mirrors. Curious and adventurous, Ila is always under her mother’s strict supervision due to her young age and yet-to-be-awakened magical powers. One day, she meets three mischievous little elves—travelers from beyond the magical gate. They quickly become friends, and Ila shares a secret: the enchanted Gao Lake holds a sealed prison for ancient frozen spirits. While skating on the lake, Ila accidentally breaks the seal, unleashing the dangerous spirits. To stop the threat, the Snow Queen sends Ila and her new friends to the human world to find Kai and Gerda—the only ones who can help. Ila’s journey begins as she enters a new world to make up for her mistake and discover her true power."
    },

    "Một tổ chức lừa đảo trực tuyến vừa bị triệt phá. Một bác sĩ nổi tiếng, thành đạt - Tiến sĩ Veronica Yu, được cho là nạn nhân, và chàng trai trẻ Joe Lee, được nhìn thấy gần hang ổ của tổ chức lừa đảo. Khi ranh giới giữa giả dối và cảm xúc dần xóa nhòa, tình yêu liệu có thật sự tồn tại hay chỉ là một màn kịch hoàn hảo?": {
        en: "A major online scam operation has just been taken down. Among the victims is the renowned and successful Dr. Veronica Yu. Nearby the gang’s hideout, a young man named Joe Lee is spotted. As the line between deception and emotion begins to blur, the question arises—can true love exist, or is it just a perfectly crafted illusion?"
    },

    "Một người đàn ông không thể cảm nhận nỗi đau thể xác đã biến căn bệnh hiếm gặp của mình thành lợi thế bất ngờ trong cuộc chiến sinh tử để giải cứu cô gái trong mơ.": {
        en: "A man who cannot feel physical pain turns his rare condition into a surprising advantage in a life-or-death battle to rescue the girl of his dreams."
    },

    "Phim lấy bối cảnh 2 năm sau các sự kiện ở phần 1. Lúc này, Gemma phát hiện công nghệ sản xuất MEGAN đã bị đánh cắp. Kẻ gian đã tạo ra một robot AI khác với chức năng tương tự MEGAN, nhưng được trang bị sức mạnh chiến đấu \"khủng\" hơn mang tên Amelia. Để \"đối đầu\" với Amelia, Gemma buộc phải \"hồi sinh\" và cải tiến MEGAN, hứa hẹn một trận chiến \"nảy lửa\" trên màn ảnh vào năm 2025.": {
        en: "Set two years after the events of the first film, Gemma discovers that the technology behind MEGAN has been stolen. A new AI robot named Amelia has been created—similar to MEGAN but equipped with extreme combat capabilities. To stand a chance against Amelia, Gemma must bring MEGAN back and enhance her powers. A fiery showdown is set to explode on screen in 2025."
    },
    "Kayara, một thiếu nữ xinh đẹp và mạnh mẽ, quyết tâm trở thành nữ sứ giả đầu tiên của Đế chế Inca. Trên hành trình đầy thử thách, cô gái phải vượt qua nhiều khó khăn và sự hiểm trở để bảo vệ thành phố Vàng khỏi những nguy cơ khai thác và cứu bạn bè, gia đình khỏi những mối đe dọa bất ngờ. Trong hành trình đầy thử thách đó, Kayara học được rằng sức mạnh thực sự không chỉ nằm ở thể chất mà còn ở sức mạnh của trí tuệ và sự đoàn kết.": {
        en: "Kayara, a beautiful and strong young woman, is determined to become the first female messenger of the Inca Empire. On her perilous journey, she must overcome numerous challenges and dangers to protect the Golden City from exploitation and save her friends and family from unexpected threats. Along the way, Kayara learns that true strength lies not only in physical power, but also in intelligence and unity."
    },

    "Thế Giới Khủng Long: Tái Sinh lấy bối cảnh 5 năm sau phần phim Thế Giới Khủng Long: Lãnh Địa, môi trường Trái đất đã chứng tỏ phần lớn là không phù hợp với khủng long. Nhiều loài thằn lằn tiền sử được tái sinh đã chết. Những con chưa chết đã rút lui đến một vùng nhiệt đới hẻo lánh gần phòng thí nghiệm. Địa điểm đó chính là nơi bộ ba Scarlett Johansson, Mahershala Ali và Jonathan Bailey dấn thân vào một nhiệm vụ cực kỳ hiểm nguy.": {
        en: "Jurassic World: Rebirth is set five years after the events of Jurassic World: Dominion. Earth’s environment has proven mostly unsuitable for dinosaurs. Many resurrected species have died off, and the remaining ones have retreated to a remote tropical region near a laboratory. It is there that the trio—Scarlett Johansson, Mahershala Ali, and Jonathan Bailey—embark on a highly dangerous mission."
    },

    "Phần tiếp theo về cuộc đời của họa sĩ webtoon Jun và những tình huống hài hước.": {
        en: "The next chapter in the life of webtoon artist Jun, filled with new hilarious situations and quirky encounters."
    },

    "Câu chuyện kinh dị về người chết sống dậy tại một ngôi làng chuyên nghề mai táng.": {
        en: "A chilling horror tale about the dead rising in a village known for its centuries-old burial traditions."
    },

    "Goro là một bác sĩ phụ khoa trong độ tuổi 30 – cũng là fan cứng của cô nàng thần tượng Ai Hoshino. Tin tức Ai tạm ngừng hoạt động khiến Goro choáng váng, nhưng Goro không biết rằng anh đang đứng trước một bước ngoặt thay đổi hoàn toàn mối quan hệ giữa anh và Ai – cũng như bi kịch đang đón chờ họ trước mắt. Một kế hoạch trả thù tàn khốc cho nữ thần tượng nổi tiếng chuẩn bị bắt đầu.": {
        en: "Goro, a gynecologist in his 30s, is a die-hard fan of pop idol Ai Hoshino. When news breaks that Ai is taking a hiatus, Goro is devastated—unaware that he’s about to face a life-altering twist that will change his connection with her forever. A harrowing plan for revenge surrounding the famous idol is about to unfold."
    },
    "Vào một đêm mưa, thi thể Gia Kỳ - con gái của cảnh sát Lạc Nhất Ngôn phát hiện tử vong. Vì không đủ bằng chứng kết tội, Khâu Tuấn Văn (nghi phạm) được thả tự do. Lạc Nhất Ngôn rời khỏi lực lượng cảnh sát. Thế nhưng, những cái chết không hề dừng lại, Lạc Nhất Ngôn nhận ra nhiều cô gái khác cũng bị sát hại dã man với cách thức giống nhau khiến ông tin rằng hung thủ thực sự vẫn còn đang nhởn nhơ ngoài vòng pháp luật. Qua quá trình điều tra, ông dần tìm ra nhân chứng duy nhất chứng kiến cảnh phạm tội của hung thủ. Đáng tiếc thay, nhân chứng lại là một cô bé thiểu năng trí tuệ. Bao nhiêu biến cố dần ập đến khiến người cha, người chồng, Lạc Nhất Ngôn gần như ngã quỵ… Liệu rằng Lạc Nhất Ngôn sẽ buông bỏ hiện thực hay ông sẽ vùng lên giành lại công lý cho con gái bị sát hại thảm thương?": {
        en: "On a rainy night, the body of Jia Ky — daughter of police officer Lac Nhat Ngon — is found dead. Due to a lack of evidence, the suspect, Khau Tuan Van, is released. Devastated, Lac Nhat Ngon resigns from the police force. But the murders don't stop. More girls are killed in a brutal, similar fashion, convincing him that the real killer is still at large. As he investigates, he discovers the only witness is a mentally challenged girl. Overwhelmed by tragedy, will Lac Nhat Ngon surrender to despair or rise to seek justice for his daughter?"
    },

    "Paul Atreides hợp sức với tộc Fremen và tìm cách trả thù những kẻ đã hủy diệt gia đình mình. Cuộc chiến vũ trụ bắt đầu với những âm mưu và sức mạnh khủng khiếp.": {
        en: "Paul Atreides joins forces with the Fremen to avenge those who destroyed his family. A galactic war begins, filled with terrifying power and relentless conspiracies."
    },

    "Buổi hẹn hò đầu tiên sau nhiều năm của Violet nhanh chóng trở thành ác mộng khi cô nhận được những tin nhắn ẩn danh kỳ lạ. Kẻ gửi đe dọa giết con trai và em gái cô nếu cô không làm theo yêu cầu của hắn.": {
        en: "Violet's first date in years turns into a nightmare when she receives strange anonymous messages. The sender threatens to kill her son and sister unless she complies with his demands."
    },

    "San mơ ngày trở lại gây dựng sự nghiệp, ai ngờ lại \"trượt chân\" vào lưới tình với Momo. Dù bị ông cậu khó tính Sanan ra sức cấm cản, anh chàng vẫn quyết tâm giành lấy chân ái đời mình. Hành trình chinh phục tình yêu của San bỗng chốc trở thành một chuỗi tình huống oái oăm, dở khóc dở cười!": {
        en: "San dreams of rebuilding his career, only to unexpectedly fall head over heels for Momo. Despite strong opposition from his strict uncle Sanan, he is determined to fight for true love. San’s pursuit of romance spirals into a series of awkward and hilariously chaotic situations."
    },

    "Trước bối cảnh hậu tận thế, chú mèo xám nhút nhát, vốn luôn sợ nước phải rời bỏ vùng an toàn khi căn nhà thân yêu bị cuốn trôi bởi cơn lũ dữ. Trên hành trình vượt đại dương mênh mông, chú mèo cùng những người bạn đồng hành (Capybara, chó Labrador Retriever, Vượn Cáo, chim Thư ký) phải học cách vượt qua nỗi sợ và chấp nhận những điểm khác biệt để cùng nhau tồn tại.": {
        en: "In a post-apocalyptic world, a timid gray cat with a fear of water is forced to leave its safe haven after a devastating flood sweeps away its home. On a journey across the vast ocean, the cat and its companions—a Capybara, a Labrador Retriever, a Lemur, and a Secretary Bird—must learn to overcome fear and embrace their differences to survive together."
    },
    "Biệt đội Bad Guys đang cố gắng lấy lại sự tin tưởng của mọi người sau khi hoàn lương, nhưng mọi nỗ lực sụp đổ khi họ bị kéo vào \"phi vụ cuối cùng\" do nhóm Bad Girls cầm đầu. Liệu họ sẽ giữ vững lý tưởng chính nghĩa, hay lại bị cuốn vào con đường tội phạm đã từng cố gắng rời bỏ?": {
        en: "The Bad Guys are trying to regain the public's trust after turning over a new leaf, but their efforts collapse when they're dragged into one last heist led by the Bad Girls. Will they stick to their newfound path of justice, or be lured back into the criminal world they tried so hard to escape?"
    },

    "Sau 22 năm, phim teen đình đám một thời “Freaky Friday” sẵn sàng trở lại với phần tiếp theo mang tên “Freakier Friday”. Giờ đây Anna đã trở thành một người mẹ, cô có một cô con gái tên Harper. Anna cũng có một cô con gái là con riêng của chồng, tên Lily, người sẽ gọi cô là mẹ kế. Lần này, phép màu không chỉ hoán đổi Anna và mẹ Tess, mà hai cô con gái cũng “nhập cuộc”. Cụ thể, Anna hoán đổi cơ thể với Harper, còn mẹ Tess hoán đổi với Lily.": {
        en: "After 22 years, the iconic teen film “Freaky Friday” returns with a sequel titled “Freakier Friday”. Anna is now a mother with a daughter named Harper, and a stepdaughter named Lily from her husband’s previous marriage. This time, the magical body swap doesn’t just involve Anna and her mother Tess—it also includes the daughters. Anna switches bodies with Harper, while Tess switches with Lily."
    },

    "Tổ đội săn lùng và tiêu diệt các thế lực tôn thờ quỷ dữ với những sức mạnh siêu nhiên khác nhau gồm “tay đấm” Ma Dong-seok, Seohuyn (SNSD) và David Lee hứa hẹn mở ra cuộc chiến săn quỷ khốc liệt nhất dịp lễ 30/4 này!": {
        en: "A demon-hunting squad wielding different supernatural powers—including the powerhouse Ma Dong-seok, Seohyun (SNSD), and David Lee—promises to bring the most intense demon-slaying battle this April 30th holiday!"
    },

    "Lấy cảm hứng từ trò chơi quen thuộc Năm Mười, câu chuyện xoay quanh một nhóm bạn cùng nhau đi nghỉ dưỡng tại Đà Lạt. Chuyến đi tưởng như chữa lành bỗng nhiên trở thành tai hoạ khi họ cùng chơi trò Năm Mười và một bí mật kinh hoàng năm xưa được hé lộ.": {
        en: "Inspired by the popular hide-and-seek game 'Nam Muoi', the story follows a group of friends vacationing in Da Lat. What was meant to be a healing getaway turns into a nightmare as the game unveils a terrifying secret from the past."
    },

    "Một nhân viên môi giới bất động sản buộc phải trở lại cuộc sống tội phạm mà anh đã từ bỏ khi người bạn đồng phạm cũ bất ngờ xuất hiện với một lời cảnh báo bí ẩn. Đồng thời, anh trai của anh một trùm tội phạm cũng đang ráo riết truy tìm anh. Anh phải đối mặt với quá khứ và những bí mật chưa từng được phơi bày.": {
        en: "A real estate broker is forced back into the criminal life he left behind when an old accomplice shows up with a mysterious warning. Meanwhile, his brother—a notorious crime boss—is also hunting him down. He must confront his dark past and long-buried secrets."
    },
    "Bị ám ảnh bởi những lời kêu gọi từ bóng tối, Sarah một nữ sinh Trong trường Đạo quyết tâm trở về quê nhà để làm rõ thân phận của mình. Bước chân về làng, nơi giờ đây trở thành địa điểm để phá thai trái phép, Sarah phải đối mặt với sự xa lánh bởi những kẻ không có đức tin. Cô cũng không biết chính sự có mặt của mình đã làm thức tỉnh oan hồn của mẹ cô - người đã bị giết chết trong lúc cố sinh ra cô. Cả ngôi làng giờ đây phải lãnh nghiệp báo mà họ đã gây ra nhiều năm về trước.": {
        en: "Haunted by whispers from the darkness, Sarah—a devout student—returns to her hometown to uncover the truth about her identity. Her village has become a secret site for illegal abortions, and she is shunned by those who have lost their faith. Unbeknownst to her, her return awakens the tormented spirit of her mother, who was murdered during Sarah's birth. Now, the entire village must face the consequences of the sins they committed years ago."
    },

    "Một tên tài xế taxi đưa một cặp đôi tới một con đường hẻo lánh bị ma ám, tiết lộ động cơ ghê rợn cùng ý định thật sự của hắn.": {
        en: "A taxi driver takes a couple to a remote, haunted road, slowly revealing his sinister motives and terrifying true intentions."
    },

    "Jack, một sĩ quan quân đội đóng tại Istanbul, bị chia cắt với gia đình khi họ đi du lịch Nhật Bản. Trong kỳ nghỉ, cậu con trai út của anh, Kyle, suýt chết đuối dưới hồ. Nhưng sau tai nạn đó, Kyle không còn là chính mình nữa—có điều gì đó u ám và đáng sợ đang thay đổi cậu bé. Cảm nhận được mối nguy hiểm vô hình, Jack lao vào cuộc tìm kiếm sự thật, khám phá những truyền thuyết cổ xưa của Nhật Bản. Anh sớm nhận ra nỗi kinh hoàng: con trai mình có thể đã trở thành mục tiêu của Kappa—một con quỷ nước cổ đại khát máu. Với thời gian cạn dần, Jack phải chiến đấu với thế lực tà ác để giành lại con trai trước khi linh hồn của Kyle bị Kappa chiếm đoạt mãi mãi, cuốn cả gia đình anh vào bóng tối kinh hoàng.": {
        en: "Jack, a military officer stationed in Istanbul, is separated from his family while they're on vacation in Japan. During the trip, his youngest son Kyle nearly drowns in a lake—but after the accident, Kyle is no longer the same. A dark and terrifying force begins to change him. Sensing an invisible danger, Jack embarks on a desperate search for answers, uncovering ancient Japanese legends. He soon faces a chilling revelation: his son may be the target of the Kappa—an ancient, bloodthirsty water demon. With time running out, Jack must confront the dark forces and save his son before Kyle’s soul is lost forever, dragging the entire family into a nightmare."
    },

    "Ai trong team này cũng từng làm việc ác, giờ là lúc làm việc ác cùng nhau. Các thành phần bất hảo trong vũ trụ điện ảnh Marvel giờ đây đã được triệu tập trở thành một nhóm gọi là “Biệt Đội Sấm Sét”, để làm những nhiệm vụ nguy hiểm bậc nhất mà có thể sẽ thay đổi con người, cuộc đời họ mãi mãi.": {
        en: "Every member of this team has done bad things—now it’s time to do bad things together. The misfits of the Marvel Cinematic Universe have been assembled as the 'Thunderbolts', tasked with taking on the most dangerous missions imaginable—missions that could change who they are and what they stand for, forever."
    },
    "Mùa hè tới đây, Warner Bros. Pictures sẽ mang “Superman” - phim điện ảnh đầu tiên của DC Studios đến các rạp chiếu trên toàn cầu. Với phong cách riêng biệt của mình, James Gunn sẽ khắc họa người hùng huyền thoại trong vũ trụ DC hoàn toàn mới, với sự kết hợp độc đáo của các yếu tố hành động đỉnh cao, hài hước và vô cùng cảm xúc. Một Superman với lòng trắc ẩn và niềm tin vào sự thiện lương của con người sẽ xuất hiện đầy hứa hẹn trên màn ảnh.": {
        en: "This summer, Warner Bros. Pictures brings 'Superman'—the first theatrical release from DC Studios—to cinemas worldwide. With his distinct storytelling style, James Gunn reimagines the legendary hero in a brand-new DC Universe, blending thrilling action, humor, and heartfelt emotion. This Superman, full of compassion and faith in the goodness of humanity, is set to soar onto the big screen with great promise."
    },

    "Câu chuyện về một chàng trai trẻ với ước mơ trở thành thợ săn rồng, nhưng định mệnh lại đưa đẩy anh đến tình bạn bất ngờ với một chú rồng.": {
        en: "The story of a young man who dreams of becoming a dragon hunter, only to find himself forming an unexpected friendship with a dragon."
    },

    "Bộ phim hài giả tưởng về cuộc phiêu lưu của Mickey.": {
        en: "A fantasy comedy about Mickey’s whimsical adventure."
    },

    "Dan-bi vốn mơ ước trở thành một tác giả truyện thiếu nhi, nhưng trớ trêu thay, cô lại khởi đầu sự nghiệp tại Đội Bảo vệ Thanh thiếu niên, nơi chuyên kiểm duyệt nội dung khiêu dâm bất hợp pháp. Một ngày nọ, Dan-bi vô tình gây ra tai nạn và phải bồi thường một khoản tiền khổng lồ cho CEO Hwang – ông trùm trong ngành văn học mạng 18+. Từ đây, cô buộc phải ký thỏa thuận viết truyện người lớn để trả nợ. Vốn chưa từng viết truyện người lớn, Dan-bi gặp đủ tình huống dở khóc dở cười. Nhưng nhờ sự cổ vũ của đồng nghiệp Jung-seok - người đang vật lộn với chứng khó “lên”, và nhờ vốn sống phong phú từ hội bạn thân mê buôn chuyện giường chiếu, cô bỗng phát hiện ra tài năng sáng tác thiên phú mà chính mình cũng không ngờ tới…": {
        en: "Dan-bi dreams of becoming a children's book author, but ironically starts her career at the Youth Protection Division, which monitors illegal adult content. One day, she causes an accident and ends up owing a huge amount to CEO Hwang—the kingpin of the adult web fiction industry. Forced to sign a contract to write adult stories to repay the debt, Dan-bi finds herself hilariously out of her depth. With encouragement from her colleague Jung-seok—who struggles with performance issues—and support from her gossip-loving friends, she discovers a surprising talent for writing spicy fiction she never knew she had."
    },

    "Charlie Heller (Rami Malek) là một chuyên gia giải mã thiên tài nhưng sống khép kín, làm việc cho CIA. Cuộc đời anh bỗng chốc đảo lộn khi vợ anh bị sát hại trong một vụ tấn công khủng bố ở London. Khi cấp trên từ chối hành động, Charlie quyết định tự mình truy lùng những kẻ đứng sau, dấn thân vào hành trình báo thù đầy nguy hiểm trên toàn cầu, nơi trí tuệ sắc bén trở thành vũ khí tối thượng giúp anh vượt qua mọi kẻ truy đuổi.": {
        en: "Charlie Heller (Rami Malek) is a brilliant but reclusive cryptanalyst working for the CIA. His life is turned upside down when his wife is killed in a terrorist attack in London. When his superiors refuse to act, Charlie takes matters into his own hands, embarking on a perilous global quest for revenge—where his razor-sharp intellect becomes his greatest weapon against those who pursue him."
    },
    "Hè 2025 này cùng cậu bé Elio chu du khám phá thiên hà tại CGV. Elio (Cậu Bé Đến Từ Trái Đất) - Dự kiến khởi chiếu 20.06.2025": {
        en: "This summer 2025, join young Elio on a galactic adventure at CGV. *Elio (The Boy from Earth)* – Coming to theaters on June 20, 2025."
    },

    "Menn, một tên trộm cắp đang làm tay trong cho cảnh sát, đồng thời cũng là một gã trai thẳng chính hiệu. Ngày nọ, Menn vô tình nhặt được một bao lì xì đỏ bí ẩn và bị ràng buộc bởi khế ước siêu nhiên, bắt anh phải kết hôn với một hồn ma. Không dừng lại ở đó, số phận càng trớ trêu hơn khi “vợ” của Menn không chỉ là người cõi âm, mà còn là một “mỹ” vong dễ thương với tư tưởng cấp tiến tên Titi. Menn buộc phải giúp Titi tìm ra sự thật đằng sau vụ tai nạn cướp đi sinh mạng của cậu để Titi được siêu thoát và trả lại bình yên cho mình. Trùng hợp làm sao, tất cả đầu mối đều dẫn đến vụ buôn ma túy bất hợp pháp do Menn và Goi, nữ cảnh sát lớn tuổi mà Menn yêu mến, đang điều tra. Tin rằng việc phá án sẽ có lợi cho sự nghiệp và tình yêu của mình, Menn quyết định tham gia phi vụ bất bình thường này để giúp Titi, từ đó tạo nên một mối liên kết không tưởng giữa đồng tính và trai thẳng, giữa người sống và kẻ chết.": {
        en: "Menn, a straight thief secretly working for the police, stumbles upon a mysterious red envelope that binds him to a supernatural contract—he must marry a ghost. As fate would have it, his new 'wife' is Titi, a cute and progressive spirit. To free himself, Menn must help Titi uncover the truth behind the accident that took his life. Coincidentally, the clues point to an illegal drug trafficking case Menn and the older female officer he admires, Goi, are investigating. Believing solving the case will benefit both his career and love life, Menn joins this bizarre mission, forging an unlikely connection between the living and the dead, between straight and queer."
    },

    "Chào mừng bạn đến với thế giới của Minecraft, nơi sự sáng tạo không chỉ giúp bạn chế tạo mà còn là yếu tố quan trọng để sống sót! Bốn kẻ lạc lõng - Garrett “The Garbage Man” Garrison (Momoa), Henry (Hansen), Natalie (Myers) và Dawn (Brooks) - bất ngờ gặp rắc rối khi họ bị kéo qua cánh cửa bí ẩn dẫn đến Overworld: một thế giới kỳ lạ được tạo bởi những khối lập phương và phát triển nhờ vào trí tưởng tượng. Để trở về nhà, họ cần phải làm chủ được thế giới này (và bảo vệ nó khỏi những thực thể tà ác như Piglins và Thây Ma) trong khi dấn thân vào chuyến phiêu lưu màu nhiệm với một thợ chế tạo chuyên nghiệp và khó lường - Steve (Black). Chuyến hành trình này sẽ thách thức sự can đảm của cả năm người, thúc đẩy họ tìm lại với những phẩm chất làm nên sự đặc biệt của riêng mình,… đồng thời là những kỹ năng cần thiết để trở lại với thế giới thật.": {
        en: "Welcome to the world of *Minecraft*, where creativity is not just for crafting but also key to survival! Four misfits—Garrett 'The Garbage Man' Garrison (Momoa), Henry (Hansen), Natalie (Myers), and Dawn (Brooks)—are thrown into trouble when they are pulled through a mysterious portal into the Overworld: a strange land built of cubes and fueled by imagination. To return home, they must master this world (and protect it from evil forces like Piglins and Zombies) while embarking on a magical journey alongside a wild and unpredictable crafter—Steve (Black). This adventure will test their courage, push them to rediscover their unique strengths… and gain the skills needed to get back to the real world."
    },

    "Vì mưu sinh, một cử nhân thất nghiệp lén cha chở một thi thể nữ về Tây Nguyên ngay giữa đêm khuya. Trên hành trình, anh buộc phải đối mặt với một thế giới siêu nhiên đầy rẫy vong linh, một cô gái bí ẩn anh đem lòng tơ tưởng và một sự thật hắc ám gắn liền với chiếc xe cứu thương mà anh đang cầm lái": {
        en: "For the sake of livelihood, an unemployed graduate secretly transports a female corpse to the Central Highlands in the dead of night. Along the way, he confronts a supernatural world full of restless spirits, a mysterious girl he falls for, and a dark secret tied to the ambulance he’s driving."
    },

    "Nhà Gia Tiên xoay quanh câu chuyện đa góc nhìn về các thế hệ khác nhau trong một gia đình, có hai nhân vật chính là Gia Minh (Huỳnh Lập) và Mỹ Tiên (Phương Mỹ Chi). Trở về căn nhà gia tiên để quay các video “triệu view” trên mạng xã hội, Mỹ Tiên - một nhà sáng tạo nội dung thuộc thế hệ Z vốn không tin vào chuyện tâm linh, hoàn toàn mất kết nối với gia đình, bất ngờ nhìn thấy Gia Minh - người anh trai đã mất từ lâu. Để hồn ma của Gia Minh có thể siêu thoát và không tiếp tục làm phiền mình, Mỹ Tiên bắt tay cùng Gia Minh lên kế hoạch giữ lấy căn nhà gia tiên đang bị họ hàng tranh chấp, đòi ông nội chia tài sản. Đứng trước hàng loạt bí mật động trời trong căn nhà gia tiên, liệu Mỹ Tiên có vượt qua được tất cả để hoàn thành di nguyện của Gia Minh?": {
        en: "*House of Ancestors* tells a multi-perspective story about different generations in a family, focusing on Gia Minh (Huỳnh Lập) and Mỹ Tiên (Phương Mỹ Chi). Returning to her ancestral home to film viral videos, Gen Z content creator Mỹ Tiên—who doesn’t believe in the spiritual—suddenly sees her long-lost brother Gia Minh’s ghost. To help his spirit move on, she agrees to team up with him to protect the ancestral house from greedy relatives fighting over inheritance. But with dark secrets looming in every corner, will Mỹ Tiên overcome it all and fulfill Gia Minh’s last wish?"
    },

    "Mắc kẹt trong cuộc sống thực tại rối ren, cả hai quay trở lại quê nhà để có một khởi đầu mới, để rồi phát hiện một thế lực ác quỷ đang nhăm nhe chờ đợi họ.": {
        en: "Trapped in the chaos of real life, the couple returns to their hometown for a fresh start—only to discover an evil force lurking, waiting for them in the shadows."
    },
    "Nhân dịp kỷ niệm 50 năm đất nước hoà bình này còn phim nào thoả được nỗi niềm thưởng thức thước phim thời chiến đầy hào hùng như Địa Đạo: Mặt Trời Trong Bóng Tối. Nay còn có thêm định dạng 4DX cho khán giả trải nghiệm chui hầm dưới lòng Củ Chi đất thép.": {
        en: "On the 50th anniversary of national peace, few films can match the stirring wartime spirit like *The Tunnel: Sun in the Shadows*. Now available in immersive 4DX format, audiences can experience crawling through the legendary Cu Chi tunnels of the Iron Land firsthand."
    }, "Câu chuyện trở lại với ngôi làng Xì Trum, nơi mà mỗi ngày đều là lễ hội. Bỗng một ngày, sự yên bình của ngôi làng bị phá vỡ khi Tí Vua bị bắt cóc một cách bí ẩn bởi hai phù thủy độc ác Gà Mên và Cà Mên. Từ đây, Tí Cô Nương phải dẫn dắt các Tí đi vào thế giới thực để giải cứu ông. Với sự giúp đỡ của những người bạn mới, các Tí sẽ bước vào cuộc phiêu lưu khám phá định mệnh của mình để cứu lấy vũ trụ.": {
        en: "The story returns to the Smurf village, where every day is a celebration. One day, the village's peace is shattered when Papa Smurf is mysteriously kidnapped by two wicked sorcerers, Gargamel and Caramel. Smurfette must lead the Smurfs into the real world to rescue him. With the help of new friends, the Smurfs embark on an adventure to discover their destiny and save the universe."
    },

    "Một bộ phim khoa học viễn tưởng hoành tráng về cuộc chiến giữa các thiên hà.": {
        en: "An epic science fiction film about a battle between galaxies."
    },

    "Oán Linh Nhập Xác xoay quanh hành trình đầy bí ẩn của hai chị em gái Hanif và Isti trong căn nhà ma quái. Mồ côi cha mẹ, chuyển lên thành phố sống từ lâu, Hanif và Isti bất ngờ phải trở về quê nhà sau cuộc gọi từ người dì, thông báo rằng chú của họ đang gặp nguy kịch. Luôn miệng cầu xin hai chị em tha thứ, chú Khair qua đời trong tình trạng yếu ớt và lạnh cóng, còn Hanif và Isti bắt đầu trải qua những sự việc kinh hoàng, thậm chí đe dọa đến mạng sống. Khi người chú không hề siêu thoát mà hóa thành oan hồn đem thảm họa đến căn nhà, Hanif và Isti phải cùng nhau vượt qua, nhưng cũng từ đó khám phá ra những bí mật bị chôn giấu ở nơi đây, về cái chết thảm khốc của cha mẹ và những thành viên khác trong gia đình mình.": {
        en: "*Possessed Spirit* follows the mysterious journey of two sisters, Hanif and Isti, in a haunted house. Orphaned and long relocated to the city, they are suddenly summoned back to their hometown after a call from their aunt, informing them that their uncle is in critical condition. Pleading for their forgiveness, Uncle Khair dies in a frail, frozen state—marking the start of horrifying events that threaten their lives. As his spirit lingers and becomes a vengeful ghost, Hanif and Isti must face the terrors of the house while uncovering long-buried secrets about the tragic deaths of their parents and other family members."
    },
    "Một cậu bé mơ mộng tập làm siêu anh hùng ngẫu nhiên bước vào cuộc hành trình giải cứu chú hổ ngơ ngác đang bị săn đuổi bởi nhóm thợ săn dữ tợn.": {
        en: "A dreamy boy aspiring to become a superhero stumbles into an unexpected journey to rescue a bewildered tiger being hunted by a group of fierce hunters."
    },

    "Một đoàn thám hiểm vũ trụ sử dụng một hố đen mới được khám phá để du hành xuyên không gian đến những vì sao xa xôi và tìm kiếm hy vọng cho loài người. “Interstellar” là biên niên ký về cuộc phiêu lưu vĩ đại của một nhóm các nhà thám hiểm sử dụng khám phá mới về lỗ đen vũ trụ để vượt qua các giới hạn thông thường trong du hành không gian, chinh phục khoảng không mênh mông trên một chuyến hành trình xuyên dải ngân hà.. Cùng trải nghiệm một INTERSTELLAR hoàn toàn khác biệt. Siêu phẩm của đạo diễn Christopher Nolan sẽ trở lại ĐỘC QUYỀN VỚI ĐỊNH DẠNG IMAX từ ngày 28.02.2025": {
        en: "A space exploration crew uses a newly discovered black hole to travel across the cosmos in search of hope for humanity. *Interstellar* chronicles the epic journey of explorers who push beyond the limits of conventional space travel, venturing through the galaxy via a cosmic wormhole. Experience a completely new INTERSTELLAR as Christopher Nolan’s masterpiece returns EXCLUSIVELY IN IMAX from February 28, 2025."
    },

    "Ngày Xưa Có Một Chuyện Tình xoay quanh câu chuyện tình bạn, tình yêu giữa hai chàng trai và một cô gái từ thuở ấu thơ cho đến khi trưởng thành, phải đối mặt với những thử thách của số phận. Trải dài trong 4 giai đoạn từ năm 1987 - 2000, ba người bạn cùng tuổi - Vinh, Miền, Phúc đã cùng yêu, cùng bỡ ngỡ bước vào đời, va vấp và vượt qua": {
        en: "*Once Upon a Love Story* follows the journey of friendship and love between two boys and a girl from childhood to adulthood, facing the trials of fate. Spanning four stages from 1987 to 2000, the three friends — Vinh, Miền, and Phúc — experience love, the confusion of growing up, heartbreaks, and resilience as they navigate life together."
    },

    "Thám Tử Kiên là một nhân vật được yêu thích trong tác phẩm điện ảnh ăn khách của NGƯỜI VỢ CUỐI CÙNG của Victor Vũ, Thám Tử Kiên: Kỳ Không Đầu sẽ là một phim Victor Vũ trở về với thể loại sở trường Kinh Dị - Trinh Thám sau những tác phẩm tình cảm lãng mạn trước đó.": {
        en: "Detective Kiên, a beloved character from Victor Vũ’s hit film *The Last Wife*, returns in *Detective Kiên: The Headless Case*. This marks Victor Vũ’s return to his signature genres of horror and mystery after several romantic dramas."
    },

    "Christian Wolff (Ben Affleck) sở hữu tài năng giải quyết những vấn đề phức tạp. Khi một người bạn cũ bị ám sát, để lại một thông điệp mơ hồ yêu cầu \"truy tìm kế toán\", Wolff bị cuốn vào việc giải quyết vụ án. Nhận ra rằng cần phải có những biện pháp cực đoan, Wolff đã liên lạc với người anh trai xa cách và vô cùng nguy hiểm của mình, Brax (Jon Bernthal), để cùng nhau điều tra. Cùng với Phó Giám đốc Cục Tài chính Marybeth Medina (Cynthia Addai-Robinson), họ phát hiện ra một âm mưu chết người, trở thành mục tiêu của một mạng lưới sát thủ tàn bạo, sẵn sàng làm mọi thứ để chôn vùi những bí mật của mình.": {
        en: "Christian Wolff (Ben Affleck) is a brilliant problem-solver. When an old friend is murdered, leaving behind a cryptic message asking to 'find the accountant', Wolff is drawn into unraveling the case. Realizing extreme measures are needed, he contacts his estranged and dangerous brother, Brax (Jon Bernthal), to investigate. Alongside Deputy Director of the Treasury Marybeth Medina (Cynthia Addai-Robinson), they uncover a deadly conspiracy and become targets of a ruthless assassin network desperate to bury its secrets."
    },
    "Bộ phim hòa nhạc lưu diễn vòng quanh thế giới đầu tiên của ZEROBASEONE sắp ra mắt tại các rạp chiếu phim trên toàn thế giới! Đạt được những cột mốc quan trọng trong năm đầu ra mắt và thu hút 140.000 người hâm mộ tại 8 thành phố trong chuyến lưu diễn vòng quanh thế giới đầu tiên, hành trình của ZEROBASEONE cùng ZEROSE sẽ trở thành tâm điểm trên màn ảnh rộng với định dạng SCREENX, 4DX và ULTRA 4DX. Bạn sẽ được thưởng thức từ những bài hát mang tính biểu tượng như \"In Bloom\", \"Feel the POP\" và \"GOOD SO BAD\" đến \"Say My Name\" và \"Here I Am\" từ chương trình Boys Planet, những cảnh quay hậu trường chỉ có thể tìm thấy trong phim, cho đến những cuộc phỏng vấn thân mật tràn ngập cảm xúc chân thành dành cho ZEROSE.": {
        en: "ZEROBASEONE’s first-ever world tour concert film is coming to theaters worldwide! Marking major milestones in their debut year and drawing 140,000 fans across 8 cities, the journey of ZEROBASEONE and ZEROSE takes center stage on the big screen in SCREENX, 4DX, and ULTRA 4DX formats. Enjoy iconic tracks like \"In Bloom\", \"Feel the POP\", and \"GOOD SO BAD\" as well as \"Say My Name\" and \"Here I Am\" from Boys Planet. The film also includes exclusive behind-the-scenes footage and emotional, heartfelt interviews dedicated to ZEROSE."
    },

    "Phiên bản live action của series Lilo & Stitch.": {
        en: "The live-action adaptation of the beloved *Lilo & Stitch* series."
    },

    "Cuộc đời là tất thảy những lựa chọn. Tom Cruise thủ vai Ethan Hunt trở lại trong Nhiệm Vụ: Bất Khả Thi – Nghiệp Báo Cuối Cùng.": {
        en: "Life is all about choices. Tom Cruise returns as Ethan Hunt in *Mission: Impossible – Dead Reckoning*."
    }
};
